### ISSUE TITLE
Y-Offsets

### ISSUE THREAD

**Issue by hermannkleier** [mabl/pyRigolWFM#4]
I use a Rigol DS1102E. Could be that the issue cannot be observed on the DS1052.

I had a waveform recorded with "Y grid scale: 5.000e-01 V/div, Y shift: -1.500e-01 V". The information was transmitted in the wfm-file header and parsed by wfmutil.py correctly.

Edit: "Y shift" was -1.5 V on the DS1102E. Therefore, the value was parsed incorrectly. I missed that initially.

To convert to "real" voltages I use the formula (125 - $1) \* 0.02 + 1.5), $1 being an unsigned byte value from the data array. The results match the displayed data on the scope.

In the contrary, the "wfmutil.py csv" values are shifted by -1.65V. I.e., instead of real 0V, the csv-file contains -1.65V.

Just a guess: Looks like "Y shift" is parsed too small (by a factor of 10) and considered with the wrong sign.

**Comment by mabl** [comment]
Hi Hermann,

thank you for the bug report. Did you shift the Y-Offset on the oscilloscope _after_ you have stopped the measurement? This might be related to issue #2.

**Comment by hermannkleier** [comment]
Hi Matthias,

thank you for the prompt reply.

On Sun, 8 Sep 2013, Matthias Blaicher wrote:

> Hi Hermann,
> 
> thank you for the bug report. Did you shift the Y-Offset _after_ you have stopped the measurement? This might be related to issue #2.

no, I didn't. I had observed that the sequence of setups is critical
for the Rigol device. So I marked down the procedure. That way I got a
more detailed protocol (and the context) at

http://cross.kleier.selfhost.me/1wire_rigol.php

It is just a notepad, though.

Greetings,

Hermann

**Comment by mabl** [comment]
Hi Hermann,

you were right... The shift calculation was wrong the whole time. I've fixed the problem and it should work for you now. I'm sorry for your troubles.

**Comment by hermannkleier** [comment]
Hi Matthias,

On Mon, 9 Sep 2013, Matthias Blaicher wrote:

thanks a lot for the quick fix.

> Hi Hermann,
> 
> you were right... The shift calculation was wrong the whole
> time. I've fixed the problem and it should work for you now. I'm
> sorry for your troubles.

And thank you for sharing the code.

Hermann
