### ISSUE TITLE
DS1104Z unsupported.

### ISSUE THREAD

**Issue by joewa** [mabl/pyRigolWFM#8]
This is the error I got:
python wfmutil.py info NewFile3.wfm
Format does not follow the known file format. Try the --forgiving option.
If you'd like to help development, please report this error:

Field magic == 42405 not met, got 65281

I cloned the repository and added an example wfm file. This is the repo https://github.com/joewa/pyRigolWFM.git
Channel 2-4 was measured.

Cheers
Jörg

**Comment by ghost** [comment]
I got this identical error, with my wfm coming from a DS1074Z.

**Comment by jyviko** [comment]
Got the same error. Any help with this issue?
Field magic == 42405 not met, got 65281
Attaching a file: http://www24.zippyshare.com/v/mOwybSWG/file.html
Any help anyone?
Cheers,
Iraklis

**Comment by mabl** [comment]
Both the DS1074Z and  DS1104Z are a new type of device running a fundamentally different firmware than the DS1052E series. 

Without documentation or an own device its unfortunately impossible for me to develop a decoder for these files.

**Comment by pklaus** [comment]
I would like to inform you that there is a fork of this software that does have support for Rigol's DS1000Z series:
https://github.com/michal-szkutnik/pyRigolWfm1000Z

**Comment by mabl** [comment]
Cool. I'll have a look. I've always wanted to restructure the code of the library. Maybe I can merge the code back.
